name: pinch
description: Flutter assignment
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #requirements
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  floor: ^1.2.0
  #plus
  connectivity_plus: ^2.3.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  #requirements
  floor_generator: ^1.2.0
  build_runner: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/src/shared/presentation/l10n
  output_dir: lib/src/shared/presentation/l10n/generated
